
# 10 RAG QA Baseline (Document-Unknown Retrieval Inputs)

This notebook runs the QA stage on top of the **document-unknown** retrieval outputs.

## Objective
- Load one retrieval run (dense / hybrid / hybrid_reranked)
- Build context from retrieved chunks
- Generate answers with Gemini or run in dry-run mode
- Save QA results, manifest, and stats

## Changelog
| Version | Change |
|---|---|
| v1 | Baseline system prompt — minimal rules |
| v2 | Explicit arithmetic permission + compact format + stricter refusal. Caused over-compression regressions on qualitative questions (all 7 had gold answers 10–43 words). |
| **v3** | **Split output format by question type**: numeric → compact; qualitative → full sentence with supporting detail. Arithmetic permission and stricter refusal threshold retained from v2. |

In [15]:
import json
import time
from pathlib import Path

import pandas as pd
from tqdm import tqdm

In [16]:
RETRIEVAL_SOURCE = "hybrid_reranked"
# options:
# "dense"
# "hybrid"
# "hybrid_reranked"

# ── Prompt version tag — appended to output filenames ──────────────────────────
PROMPT_VERSION = "v3"

TOP_K_CONTEXT = 5

GENERATION_MODE = "gemini"   # "dry_run" or "gemini"
GENERATION_MODEL = "gemini-2.5-pro"

USE_QUERY_LIMIT = False
QUERY_LIMIT = 20

SLEEP_BETWEEN_CALLS = 1.0

qa_config = {
    "retrieval_source": RETRIEVAL_SOURCE,
    "prompt_version": PROMPT_VERSION,
    "top_k_context": TOP_K_CONTEXT,
    "generation_mode": GENERATION_MODE,
    "generation_model": GENERATION_MODEL if GENERATION_MODE == "gemini" else None,
    "document_known": False
}

qa_config

{'retrieval_source': 'hybrid_reranked',
 'prompt_version': 'v3',
 'top_k_context': 5,
 'generation_mode': 'gemini',
 'generation_model': 'gemini-2.5-pro',
 'document_known': False}

In [17]:
CURRENT_DIR = Path.cwd()

if CURRENT_DIR.name == "notebooks":
    BASE_DIR = CURRENT_DIR.parent
else:
    BASE_DIR = CURRENT_DIR

DATA_DIR = BASE_DIR / "data"
INTERIM_DIR = DATA_DIR / "interim"
PROCESSED_DIR = DATA_DIR / "processed"

QA_DIR = PROCESSED_DIR / "qa_results"
RETRIEVAL_DIR = PROCESSED_DIR / "retrieval_results"

WORKING_DATASET_CSV_PATH = INTERIM_DIR / "financebench_open_source_working.csv"
WORKING_DATASET_PARQUET_PATH = INTERIM_DIR / "financebench_open_source_working.parquet"

QA_DIR.mkdir(parents=True, exist_ok=True)

if RETRIEVAL_SOURCE == "dense":
    RETRIEVAL_RESULTS_CSV_PATH = RETRIEVAL_DIR / "retrieval_results_dense.csv"
    RETRIEVAL_RESULTS_PARQUET_PATH = RETRIEVAL_DIR / "retrieval_results_dense.parquet"
    RUN_NAME = "dense"

elif RETRIEVAL_SOURCE == "hybrid":
    RETRIEVAL_RESULTS_CSV_PATH = RETRIEVAL_DIR / "retrieval_results_hybrid.csv"
    RETRIEVAL_RESULTS_PARQUET_PATH = RETRIEVAL_DIR / "retrieval_results_hybrid.parquet"
    RUN_NAME = "hybrid"

elif RETRIEVAL_SOURCE == "hybrid_reranked":
    RETRIEVAL_RESULTS_CSV_PATH = RETRIEVAL_DIR / "retrieval_results_hybrid_reranked.csv"
    RETRIEVAL_RESULTS_PARQUET_PATH = RETRIEVAL_DIR / "retrieval_results_hybrid_reranked.parquet"
    RUN_NAME = "hybrid_reranked"

else:
    raise ValueError(f"Unknown RETRIEVAL_SOURCE: {RETRIEVAL_SOURCE}")

QA_RESULTS_CSV_PATH = QA_DIR / f"rag_qa_results_{RUN_NAME}_{PROMPT_VERSION}.csv"
QA_RESULTS_PARQUET_PATH = QA_DIR / f"rag_qa_results_{RUN_NAME}_{PROMPT_VERSION}.parquet"
QA_MANIFEST_PATH = QA_DIR / f"rag_qa_manifest_{RUN_NAME}_{PROMPT_VERSION}.csv"
QA_STATS_PATH = QA_DIR / f"rag_qa_stats_{RUN_NAME}_{PROMPT_VERSION}.json"

print("RETRIEVAL_SOURCE:", RETRIEVAL_SOURCE)
print("PROMPT_VERSION  :", PROMPT_VERSION)
print("RUN_NAME        :", RUN_NAME)
print("QA_RESULTS_CSV_PATH:", QA_RESULTS_CSV_PATH)

RETRIEVAL_SOURCE: hybrid_reranked
PROMPT_VERSION  : v3
RUN_NAME        : hybrid_reranked
QA_RESULTS_CSV_PATH: C:\Users\ntheo\Desktop\Repositories\Financial-RAG\thesis-rag\data\processed\qa_results\rag_qa_results_hybrid_reranked_v3.csv

In [18]:
if WORKING_DATASET_PARQUET_PATH.exists():
    working_df = pd.read_parquet(WORKING_DATASET_PARQUET_PATH)
elif WORKING_DATASET_CSV_PATH.exists():
    working_df = pd.read_csv(WORKING_DATASET_CSV_PATH)
else:
    raise FileNotFoundError("Working dataset not found.")

print("working_df shape:", working_df.shape)
print(working_df.columns.tolist())
working_df.head(2)

working_df shape: (150, 22)
['row_id', 'financebench_id', 'question', 'answer', 'company', 'doc_name', 'doc_type', 'doc_period', 'pdf_filename', 'pdf_path', 'question_type', 'question_reasoning', 'justification', 'evidence', 'domain_question_num', 'dataset_subset_label', 'company_doc', 'gics_sector', 'doc_link', 'normalized_doc_name', 'pdf_stem', 'normalized_pdf_stem']

,row_id,financebench_id,question,answer,company,doc_name,doc_type,doc_period,pdf_filename,pdf_path,...,justification,evidence,domain_question_num,dataset_subset_label,company_doc,gics_sector,doc_link,normalized_doc_name,pdf_stem,normalized_pdf_stem
0,0,financebench_id_03029,What is the FY2018 capital expenditure amount ...,$1577.00,3M,3M_2018_10K,10k,2018,3M_2018_10K.pdf,C:\Users\ntheo\Desktop\Repositories\Financial-...,...,The metric capital expenditures was directly e...,"[{'doc_name': '3M_2018_10K', 'evidence_page_nu...",None,OPEN_SOURCE,3M,Industrials,https://investors.3m.com/financials/sec-filing...,3m 2018 10k,3M_2018_10K,3m 2018 10k
1,1,financebench_id_04672,Assume that you are a public equities analyst....,$8.70,3M,3M_2018_10K,10k,2018,3M_2018_10K.pdf,C:\Users\ntheo\Desktop\Repositories\Financial-...,...,"The metric ppne, net was directly extracted fr...","[{'doc_name': '3M_2018_10K', 'evidence_page_nu...",None,OPEN_SOURCE,3M,Industrials,https://investors.3m.com/financials/sec-filing...,3m 2018 10k,3M_2018_10K,3m 2018 10k

In [19]:
candidate_paths = [RETRIEVAL_RESULTS_PARQUET_PATH, RETRIEVAL_RESULTS_CSV_PATH]
existing_paths = [p for p in candidate_paths if p.exists()]

if not existing_paths:
    raise FileNotFoundError(f"No retrieval results found for source: {RETRIEVAL_SOURCE}")

RETRIEVAL_RESULTS_PATH = existing_paths[0]

if RETRIEVAL_RESULTS_PATH.suffix == ".parquet":
    retrieval_df = pd.read_parquet(RETRIEVAL_RESULTS_PATH)
else:
    retrieval_df = pd.read_csv(RETRIEVAL_RESULTS_PATH)

print("Using retrieval results:", RETRIEVAL_RESULTS_PATH)
print("retrieval_df shape:", retrieval_df.shape)
print(retrieval_df.columns.tolist())
retrieval_df.head(2)

Using retrieval results: C:\Users\ntheo\Desktop\Repositories\Financial-RAG\thesis-rag\data\processed\retrieval_results\retrieval_results_hybrid_reranked.parquet
retrieval_df shape: (1500, 21)
['financebench_id', 'question', 'question_clean', 'expanded_question', 'expected_doc_name', 'expected_company', 'retrieved_rank', 'rerank_score', 'previous_rank', 'rrf_score', 'dense_rank', 'dense_score', 'bm25_rank', 'bm25_score', 'chunk_id', 'retrieved_doc_id', 'chunk_index', 'chunk_text', 'char_count', 'token_estimate', 'doc_match']

,financebench_id,question,question_clean,expanded_question,expected_doc_name,expected_company,retrieved_rank,rerank_score,previous_rank,rrf_score,...,dense_score,bm25_rank,bm25_score,chunk_id,retrieved_doc_id,chunk_index,chunk_text,char_count,token_estimate,doc_match
0,financebench_id_03029,What is the FY2018 capital expenditure amount ...,What is the FY2018 capital expenditure amount ...,what is the fy2018 capital expenditure amount ...,3M_2018_10K,3M,1,0.916973,5,0.032198,...,0.676206,4.0,35.858704,3M_2018_10K_chunk_0290,3M_2018_10K,290,## NOTE 9. Supplemental Cash Flow Information\...,1348,337,True
1,financebench_id_03029,What is the FY2018 capital expenditure amount ...,What is the FY2018 capital expenditure amount ...,what is the fy2018 capital expenditure amount ...,3M_2018_10K,3M,2,0.893710,9,0.025814,...,0.661815,7.0,35.267231,COCACOLA_2017_10K_chunk_0288,COCACOLA_2017_10K,288,We expect our annual 2018 capital expenditures...,1076,269,False

In [20]:
required_retrieval_cols = [
    "financebench_id",
    "question",
    "retrieved_rank",
    "chunk_id",
    "retrieved_doc_id",
    "chunk_text",
]

missing_cols = [c for c in required_retrieval_cols if c not in retrieval_df.columns]
if missing_cols:
    raise ValueError(f"Missing required columns in retrieval_df: {missing_cols}")

print("Retrieval dataframe columns OK.")

Retrieval dataframe columns OK.

In [21]:
if USE_QUERY_LIMIT:
    keep_ids = working_df["financebench_id"].drop_duplicates().head(QUERY_LIMIT).tolist()
    working_df = working_df[working_df["financebench_id"].isin(keep_ids)].copy().reset_index(drop=True)
    retrieval_df = retrieval_df[retrieval_df["financebench_id"].isin(keep_ids)].copy().reset_index(drop=True)

print("working_df shape after optional limit:", working_df.shape)
print("retrieval_df shape after optional limit:", retrieval_df.shape)

working_df shape after optional limit: (150, 22)
retrieval_df shape after optional limit: (1500, 21)

In [22]:
base_cols = ["financebench_id", "question"]

if "answer" in working_df.columns:
    base_cols.append("answer")

if "doc_name" in working_df.columns:
    base_cols.append("doc_name")

if "company" in working_df.columns:
    base_cols.append("company")

qa_input_df = (
    working_df[base_cols]
    .drop_duplicates(subset=["financebench_id"])
    .copy()
    .reset_index(drop=True)
)

if "answer" not in qa_input_df.columns:
    qa_input_df["answer"] = None

if "doc_name" not in qa_input_df.columns:
    qa_input_df["doc_name"] = None

if "company" not in qa_input_df.columns:
    qa_input_df["company"] = None

print("qa_input_df shape:", qa_input_df.shape)
qa_input_df.head(2)

qa_input_df shape: (150, 5)

,financebench_id,question,answer,doc_name,company
0,financebench_id_03029,What is the FY2018 capital expenditure amount ...,$1577.00,3M_2018_10K,3M
1,financebench_id_04672,Assume that you are a public equities analyst....,$8.70,3M_2018_10K,3M

In [23]:
def build_context_text(group_df: pd.DataFrame, top_k: int = TOP_K_CONTEXT) -> str:
    top_group = group_df.sort_values("retrieved_rank", ascending=True).head(top_k).copy()

    parts = []
    for _, row in top_group.iterrows():
        retrieved_rank = row.get("retrieved_rank")
        retrieved_doc_id = row.get("retrieved_doc_id")
        chunk_id = row.get("chunk_id")
        chunk_text = str(row.get("chunk_text", "")).strip()

        part = (
            f"[Rank {retrieved_rank} | Doc {retrieved_doc_id} | Chunk {chunk_id}]\n"
            f"{chunk_text}"
        )
        parts.append(part)

    return "\n\n" + ("\n\n" + "-" * 80 + "\n\n").join(parts)


def get_top_chunk_id(group_df: pd.DataFrame):
    top_row = group_df.sort_values("retrieved_rank", ascending=True).iloc[0]
    return top_row.get("chunk_id")


def get_top_doc_id(group_df: pd.DataFrame):
    top_row = group_df.sort_values("retrieved_rank", ascending=True).iloc[0]
    return top_row.get("retrieved_doc_id")

In [24]:
grouped_retrieval = retrieval_df.groupby("financebench_id", sort=False)

context_records = []

for financebench_id, group in grouped_retrieval:
    context_records.append({
        "financebench_id": financebench_id,
        "context_text": build_context_text(group, top_k=TOP_K_CONTEXT),
        "top_chunk_id": get_top_chunk_id(group),
        "top_doc_id": get_top_doc_id(group),
        "n_retrieved_rows": int(len(group)),
    })

context_df = pd.DataFrame(context_records)

qa_df = qa_input_df.merge(context_df, on="financebench_id", how="left")

print("context_df shape:", context_df.shape)
print("qa_df shape:", qa_df.shape)
qa_df.head(2)

context_df shape: (150, 5)
qa_df shape: (150, 9)

,financebench_id,question,answer,doc_name,company,context_text,top_chunk_id,top_doc_id,n_retrieved_rows
0,financebench_id_03029,What is the FY2018 capital expenditure amount ...,$1577.00,3M_2018_10K,3M,\n\n[Rank 1 | Doc 3M_2018_10K | Chunk 3M_2018_...,3M_2018_10K_chunk_0290,3M_2018_10K,10
1,financebench_id_04672,Assume that you are a public equities analyst....,$8.70,3M_2018_10K,3M,\n\n[Rank 1 | Doc 3M_2018_10K | Chunk 3M_2018_...,3M_2018_10K_chunk_0196,3M_2018_10K,10

In [25]:
# ── v3: targeted fix over v2 ──────────────────────────────────────────────
# Root-cause of v2 regressions: the 'Lead with the direct answer' rule caused
# the model to over-compress qualitative/narrative answers (e.g. 'defeated'
# instead of 'The shareholder proposal...was defeated'; 'Yes' instead of
# 'Yes, CVS paid $0.55 per share...').  All 7 regressions had long gold answers
# (10-43 words) and qualitative question types.
#
# Fix: split output format rules by question type:
#   - Numeric/factual  → compact (v2 behaviour was correct here)
#   - Qualitative      → full sentence that includes the key supporting detail
# Arithmetic permission and stricter refusal threshold are kept from v2.
SYSTEM_PROMPT = """You are a financial analyst assistant answering questions from SEC filings.

Answer the question using ONLY the provided context chunks.

## Output format — choose based on question type

**Numeric or factual questions** (amounts, ratios, dates, yes/no with a single value):
- Lead with the number or value, in the units requested.
- If a calculation is needed, show the formula and intermediate values on one line, then state the final answer.
- Example: 'Operating cash flow ratio = $4,862M / $3,200M = 1.52'

**Qualitative or comparative questions** (trends, comparisons, explanations, outcomes):
- Answer in one or two complete sentences.
- Include the key supporting detail from the context (e.g. the specific percentage, the segment name, the vote outcome phrase).
- Do NOT reduce the answer to a single word or number if the question asks for context or explanation.

## Calculation rules
- You MAY perform arithmetic (addition, subtraction, multiplication, division, percentage change) using numbers explicitly stated in the context.
- You MAY derive ratios, margins, or growth rates if all required line items are present.
- Round to the precision requested in the question (default: 2 decimal places for ratios, 1 for percentages).

## When to refuse
Only say \"Insufficient evidence in the retrieved context.\" when the specific data required is genuinely absent from ALL provided chunks — not merely because the answer requires a calculation.

## Hard rules
- Do not invent numbers or cite sources outside the provided context.
- If a metric is not applicable (e.g. gross margin for a bank), state that and explain briefly using context evidence.
- Do not restate the question in your answer.
"""

def build_user_prompt(question: str, context_text: str) -> str:
    return f"""Context chunks (ranked by relevance):
{context_text}

Question: {question}

Answer:"""

In [26]:
if GENERATION_MODE == "gemini":
    import os
    os.environ["GEMINI_API_KEY"] = "AIzaSyDJBc6dSBSxqJAzgAU8kLUVC6zBxL73iIE"
    try:
        from google import genai
        gemini_client = genai.Client()
        print("Gemini client initialized.")
    except Exception as e:
        raise RuntimeError(f"Failed to initialize Gemini client: {e}")
else:
    gemini_client = None
    print("Generation mode is dry_run.")

Gemini client initialized.

In [27]:
def generate_answer(question: str, context_text: str) -> str:
    if GENERATION_MODE == "dry_run":
        return "[DRY RUN] Answer generation skipped."

    user_prompt = build_user_prompt(question=question, context_text=context_text)

    response = gemini_client.models.generate_content(
        model=GENERATION_MODEL,
        contents=user_prompt,
        config={
            "system_instruction": SYSTEM_PROMPT,
            "temperature": 0.0,
        }
    )

    if hasattr(response, "text") and response.text:
        return response.text.strip()

    return "Insufficient evidence in the retrieved context."

In [28]:
qa_records = []
manifest_records = []

for idx, row in tqdm(qa_df.iterrows(), total=len(qa_df), desc=f"Running QA for {RUN_NAME}"):
    financebench_id = row["financebench_id"]
    question = row["question"]
    expected_answer = row.get("answer")
    expected_doc_name = row.get("doc_name")
    expected_company = row.get("company")
    context_text = row.get("context_text")
    top_chunk_id = row.get("top_chunk_id")
    top_doc_id = row.get("top_doc_id")
    n_retrieved_rows = row.get("n_retrieved_rows")

    manifest_record = {
        "financebench_id": financebench_id,
        "question": question,
        "expected_doc_name": expected_doc_name,
        "status": None,
        "error_message": None,
        "top_doc_id": top_doc_id,
        "top_chunk_id": top_chunk_id,
    }

    try:
        if pd.isna(context_text) or not str(context_text).strip():
            generated_answer = "Insufficient evidence in the retrieved context."
        else:
            generated_answer = generate_answer(question=question, context_text=context_text)

        qa_records.append({
            "financebench_id": financebench_id,
            "question": question,
            "expected_answer": expected_answer,
            "expected_doc_name": expected_doc_name,
            "expected_company": expected_company,
            "retrieval_source": RETRIEVAL_SOURCE,
            "top_doc_id": top_doc_id,
            "top_chunk_id": top_chunk_id,
            "n_retrieved_rows": n_retrieved_rows,
            "context_text": context_text,
            "generated_answer": generated_answer,
            "generated_answer_len": len(str(generated_answer)),
            "doc_match": str(expected_doc_name) == str(top_doc_id),
        })

        manifest_record["status"] = "success"

    except Exception as e:
        manifest_record["status"] = "error"
        manifest_record["error_message"] = str(e)

    manifest_records.append(manifest_record)

    if GENERATION_MODE == "gemini":
        time.sleep(SLEEP_BETWEEN_CALLS)

qa_results_df = pd.DataFrame(qa_records)
qa_manifest_df = pd.DataFrame(manifest_records)

print("qa_results_df shape:", qa_results_df.shape)
print("qa_manifest_df shape:", qa_manifest_df.shape)

Running QA for hybrid_reranked: 100%|██████████| 150/150 [25:12<00:00, 10.09s/it]

qa_results_df shape: (150, 13)
qa_manifest_df shape: (150, 7)

In [29]:
qa_results_df[[
    "financebench_id",
    "question",
    "expected_answer",
    "generated_answer",
    "top_doc_id",
    "expected_doc_name",
    "doc_match"
]].head(10)

,financebench_id,question,expected_answer,generated_answer,top_doc_id,expected_doc_name,doc_match
0,financebench_id_03029,What is the FY2018 capital expenditure amount ...,$1577.00,"$1,577M",3M_2018_10K,3M_2018_10K,True
1,financebench_id_04672,Assume that you are a public equities analyst....,$8.70,"$8.74 billion\n\nThe value for ""Property, plan...",3M_2018_10K,3M_2018_10K,True
2,financebench_id_00499,Is 3M a capital-intensive business based on FY...,"No, the company is managing its CAPEX and Fixe...","Yes, 3M is a capital-intensive business, as it...",3M_2022_10K,3M_2022_10K,True
3,financebench_id_01226,What drove operating margin change as of FY202...,Operating Margin for 3M in FY2022 has decrease...,The change in 3M's operating margin in 2022 wa...,3M_2022_10K,3M_2022_10K,True
4,financebench_id_01865,"If we exclude the impact of M&A, which segment...",The consumer segment shrunk by 0.9% organically.,Insufficient evidence in the retrieved context.,3M_2022_10K,3M_2022_10K,True
5,financebench_id_00807,Does 3M have a reasonably healthy liquidity pr...,No. The quick ratio for 3M was 0.96 by Jun'23 ...,Insufficient evidence in the retrieved context.,3M_2023Q2_10Q,3M_2023Q2_10Q,True
6,financebench_id_00941,Which debt securities are registered to trade ...,Following debt securities registered under 3M'...,Insufficient evidence in the retrieved context.,3M_2023Q2_10Q,3M_2023Q2_10Q,True
7,financebench_id_01858,Does 3M maintain a stable trend of dividend di...,"Yes, not only they distribute the dividends on...","Yes, 3M maintains a stable trend of dividend d...",3M_2018_10K,3M_2023Q2_10Q,False
8,financebench_id_02987,What is the FY2019 fixed asset turnover ratio ...,24.26,Insufficient evidence in the retrieved context.,ACTIVISIONBLIZZARD_2019_10K,ACTIVISIONBLIZZARD_2019_10K,True
9,financebench_id_07966,What is the FY2017 - FY2019 3 year average of ...,1.9%,Insufficient evidence in the retrieved context.,ACTIVISIONBLIZZARD_2019_10K,ACTIVISIONBLIZZARD_2019_10K,True

In [30]:
qa_results_df.to_csv(QA_RESULTS_CSV_PATH, index=False, encoding="utf-8")
qa_results_df.to_parquet(QA_RESULTS_PARQUET_PATH, index=False)

qa_manifest_df.to_csv(QA_MANIFEST_PATH, index=False, encoding="utf-8")

print("Saved:")
print("-", QA_RESULTS_CSV_PATH)
print("-", QA_RESULTS_PARQUET_PATH)
print("-", QA_MANIFEST_PATH)

Saved:
- C:\Users\ntheo\Desktop\Repositories\Financial-RAG\thesis-rag\data\processed\qa_results\rag_qa_results_hybrid_reranked_v3.csv
- C:\Users\ntheo\Desktop\Repositories\Financial-RAG\thesis-rag\data\processed\qa_results\rag_qa_results_hybrid_reranked_v3.parquet
- C:\Users\ntheo\Desktop\Repositories\Financial-RAG\thesis-rag\data\processed\qa_results\rag_qa_manifest_hybrid_reranked_v3.csv

In [31]:
successful_generations = int((qa_manifest_df["status"] == "success").sum()) if "status" in qa_manifest_df.columns else 0
failed_generations = int((qa_manifest_df["status"] == "error").sum()) if "status" in qa_manifest_df.columns else 0

qa_stats = {
    "retrieval_source": RETRIEVAL_SOURCE,
    "document_known": False,
    "generation_mode": GENERATION_MODE,
    "generation_model": GENERATION_MODEL if GENERATION_MODE == "gemini" else None,
    "top_k_context": TOP_K_CONTEXT,
    "n_queries": int(qa_df["financebench_id"].nunique()),
    "n_result_rows": int(len(qa_results_df)),
    "n_manifest_rows": int(len(qa_manifest_df)),
    "successful_generations": successful_generations,
    "failed_generations": failed_generations,
    "results_csv": str(QA_RESULTS_CSV_PATH),
    "results_parquet": str(QA_RESULTS_PARQUET_PATH),
    "manifest_csv": str(QA_MANIFEST_PATH),
}

with open(QA_STATS_PATH, "w", encoding="utf-8") as f:
    json.dump(qa_stats, f, indent=2, ensure_ascii=False)

print("Saved stats:", QA_STATS_PATH)
qa_stats

Saved stats: C:\Users\ntheo\Desktop\Repositories\Financial-RAG\thesis-rag\data\processed\qa_results\rag_qa_stats_hybrid_reranked_v3.json

{'retrieval_source': 'hybrid_reranked',
 'document_known': False,
 'generation_mode': 'gemini',
 'generation_model': 'gemini-2.5-pro',
 'top_k_context': 5,
 'n_queries': 150,
 'n_result_rows': 150,
 'n_manifest_rows': 150,
 'successful_generations': 150,
 'failed_generations': 0,
 'results_csv': 'C:\\Users\\ntheo\\Desktop\\Repositories\\Financial-RAG\\thesis-rag\\data\\processed\\qa_results\\rag_qa_results_hybrid_reranked_v3.csv',
 'results_parquet': 'C:\\Users\\ntheo\\Desktop\\Repositories\\Financial-RAG\\thesis-rag\\data\\processed\\qa_results\\rag_qa_results_hybrid_reranked_v3.parquet',
 'manifest_csv': 'C:\\Users\\ntheo\\Desktop\\Repositories\\Financial-RAG\\thesis-rag\\data\\processed\\qa_results\\rag_qa_manifest_hybrid_reranked_v3.csv'}

In [32]:
print(qa_manifest_df["status"].value_counts(dropna=False))
qa_manifest_df[["financebench_id", "status", "error_message"]].head(10)

status
success    150
Name: count, dtype: int64

         financebench_id   status error_message
0  financebench_id_03029  success          None
1  financebench_id_04672  success          None
2  financebench_id_00499  success          None
3  financebench_id_01226  success          None
4  financebench_id_01865  success          None
5  financebench_id_00807  success          None
6  financebench_id_00941  success          None
7  financebench_id_01858  success          None
8  financebench_id_02987  success          None
9  financebench_id_07966  success          None

## Συμπέρασμα

Σε αυτό το notebook:

- φορτώσαμε ένα retrieval run (dense / hybrid / hybrid_reranked)
- χτίσαμε context από τα top retrieved chunks
- τρέξαμε QA με Gemini ή dry-run mode
- αποθηκεύσαμε QA results, manifest και stats

Το επόμενο notebook θα αξιολογήσει dense, hybrid και reranked QA outputs.